version: '2'
services:
  mktnode:
    image: "ahaschool/node-php:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/www/web:/app/web
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/zoneinfo/Shanghai:/etc/localtime
    network_mode: "bridge"
